use_frameworks!

target 'ColorfulBanner_Example' do
  pod 'ColorfulBanner', :path => '../'

  target 'ColorfulBanner_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
